### ISSUE TITLE
RedisClient::ConnectionError with pubsub

### ISSUE THREAD

**Issue by mathieumahe** [redis-rb/redis-client#118] opened 2023-05-22 10:55 UTC
Hello,

I just switched from `redis-rb` to `redis-client` and I see some connection errors on one of my production instance.

I use the code :

`$conn = RedisClient.new(reconnect_attempts: 1).pubsub` and `$conn.call('publish', event, payload.to_json)`.

After some time I see some `RedisClient::ConnectionError` `Not connected` or `Broken pipe` errors raised by 

```
/app/shared/bundle/ruby/3.0.0/gems/hiredis-client-0.14.1/lib/redis_client/hiredis_connection.rb:94:in `_write'
/app/shared/bundle/ruby/3.0.0/gems/hiredis-client-0.14.1/lib/redis_client/hiredis_connection.rb:94:in `write'
/app/shared/bundle/ruby/3.0.0/gems/redis-client-0.14.1/lib/redis_client.rb:421:in `call'
/app/releases/20230522090020/lib/pubsub_singleton.rb:69:in `publish'
```

Is the `reconnect_attempts` also used after a broken connection ? Am I missing a parameter that used to make redis-rb work and not redis-client?

Thanks for your help and for the good work!

**Comment by byroot** [comment] 2023-05-22 10:56
See: https://github.com/redis-rb/redis-client#reconnection


`redis-rb` does retry by default, and that's probably what was hiding these events to you. You can pass `reconnect_attempts: 1` to restore the old behavior.


Duplicate of https://github.com/redis-rb/redis-client/issues/116

**Comment by mathieumahe** [comment] 2023-05-22 11:04
I saw this issue and I modified my code already (as you can see in my first post) but it didn't solve my problem.

The errors are raised after few minutes/hours of connection, not when the connection is created. So I'm not sure it's the same thing than #116

**Comment by byroot** [comment] 2023-05-22 11:05
Apologies, I read a bit too fast, didn't notice it was about pubsub specifically.

**Comment by mathieumahe** [comment] 2023-05-22 11:14
That makes sense!

Thanks for your help.

**Closed** 2023-05-23 07:50 UTC
